@include('pages.administracion.ingresantes.jscripts')
@include('pages.administracion.ingresantes.confirmModal')
@extends('pages.administracion.administracion')
@section('page')
{{$dataTable->table()}}
@stop
@push('scripts')
{{$dataTable->scripts()}}
@endpush
@yield('confirmModal')
@yield('jscripts')